sudo: false
language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp grunt-cli
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: SisJdf4Tuo+MfDQoGjGTC1ZJI02KUaL4/xH7eGryht6aucDyEGVKtMWkSTxZfIHE4jYFZar0ZgN9FdarAr3eLYZrf3F2kPkBasbIbw/obiQcei13H9sVgaBlxvMkPC5W6eRVSQzTNalJBdIRDmwEFAdTgd8IWzREwojDu5scMvU=
  on:
    tags: true
    repo: T1st3/open-share-icon
